### ISSUE TITLE
Деление и умножение рациональных не оптимально

### ISSUE THREAD

**Issue by catam0rphism** [demon1234432/colloquium_c--_medium#17]
Вопрос о том, когда следует производить сокращение, а когда нет остается открытым. Принимается любой мыслепоток, рассматриваются самые безумные идеи по типу факторизации числа и все такое.

**Comment by demon1234432** [comment]
Временная мера в виде сокращения после выполнения в части функций не приведет к добру.

~~~Нет ничего более постоянного, чем временное.~~~
